In [2]:
import numpy as np
my_list = [1,2,3,4,5]
arr = np.array(my_list)
type(arr)

numpy.ndarray

In [3]:
print(arr)

[1 2 3 4 5]


In [5]:
arr.shape

(5,)

In [6]:
arr

array([1, 2, 3, 4, 5])

In [7]:
#multinested array

my_list1 = [1,2,3,4]
my_list2 = [5,6,7,8]
my_list3 = [9, 10, 11, 12]

arr = np.array([my_list1, my_list2, my_list3])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
arr.shape



(3, 4)

In [16]:
x= arr.reshape(4,3)
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [17]:
x.shape

(4, 3)

In [18]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr[3]

4

In [37]:
arr = np.arange(0,10, 2)
arr
np.linspace(1,10,50)


array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [36]:
 arr[3: ] = 100
 arr

array([  0,   2,   4, 100, 100])

In [39]:
#create arrays and reshape
np.arange(0,10).reshape(5,2)



array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [46]:
arr1 = np.arange(0,10).reshape(2,5)
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [47]:
arr2 = np.arange(0,10).reshape(2,5)
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [45]:
arr1*arr2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [48]:
np.ones((2,5), dtype=int)


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [49]:
#random  distribution
np.random.rand(3,3)

array([[0.61025735, 0.54095167, 0.93146663],
       [0.36857173, 0.94874149, 0.65079136],
       [0.73607983, 0.29331825, 0.19480626]])

In [50]:
arr_exp = np.random.rand(4,4)
arr_exp

array([[0.19778149, 0.19655721, 0.46906246, 0.66021856],
       [0.6104872 , 0.96350985, 0.19807019, 0.59032596],
       [0.17610052, 0.43192547, 0.79676014, 0.81937626],
       [0.49609434, 0.19804778, 0.56093206, 0.15840616]])

In [59]:
np.random.randint(0, 100, 8).reshape(4,2)


array([[22, 74],
       [ 8, 94],
       [84, 14],
       [40, 81]])

In [62]:
np.random.random_sample((1,5))

array([[0.68487586, 0.34327345, 0.92524131, 0.60161304, 0.94041265]])